import { Ionicons } from '@expo/vector-icons';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useState } from 'react';
import { Screen } from '@/src/components/Screen';
import { SectionTitle } from '@/src/components/SectionTitle';
import { exercises, oneArmProgression, Category } from '@/src/data';
import { colors, fonts, spacing } from '@/src/theme';

const categories: Array<'All' | Category> = ['All', 'Push', 'Pull', 'Legs'];

export default function LibraryScreen() {
  const [category, setCategory] = useState<'All' | Category>('All');
  const [query, setQuery] = useState('');
  const filtered = exercises.filter((exercise) => (category === 'All' || exercise.category === category) && exercise.name.toLowerCase().includes(query.toLowerCase()));
  return <Screen>
    <View style={styles.header}><Text style={styles.title}>Library</Text><Text style={styles.subtitle}>Movements and progressions for your practice.</Text></View>
    <View style={styles.search}><Ionicons name="search" size={18} color={colors.muted} /><TextInput accessibilityLabel="Search exercises" value={query} onChangeText={setQuery} placeholder="Search movements" placeholderTextColor={colors.muted} style={styles.input} /></View>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filters}>{categories.map((item) => <Pressable key={item} onPress={() => setCategory(item)} style={[styles.filter, category === item && styles.filterActive]}><Text style={[styles.filterText, category === item && styles.filterTextActive]}>{item}</Text></Pressable>)}</ScrollView>
    <SectionTitle title="Exercises" action={`${filtered.length} movements`} /><View style={styles.list}>{filtered.map((exercise) => <Pressable key={exercise.id} style={styles.exerciseRow}><View><Text style={styles.exerciseName}>{exercise.name}</Text><Text style={styles.detail}>{exercise.detail}</Text></View><Text style={styles.level}>{exercise.level}</Text></Pressable>)}</View>
    <SectionTitle title="Progressions" /><Pressable style={styles.progression}><View style={styles.progressionCopy}><Text style={styles.progressionName}>One-arm push-up</Text><Text style={styles.detail}>5 steps · current: assisted</Text></View><Ionicons name="arrow-forward" size={18} color={colors.ink} /></Pressable>
    {oneArmProgression.map((step, index) => <View key={step.title} style={styles.step}><View style={[styles.stepDot, step.state === 'Current' && styles.currentDot, step.state === 'Completed' && styles.doneDot]}>{step.state === 'Completed' ? <Ionicons name="checkmark" size={12} color={colors.white} /> : <Text style={styles.stepIndex}>{index + 1}</Text>}</View><Text style={[styles.stepTitle, step.state === 'Current' && styles.currentText]}>{step.title}</Text><Text style={[styles.stepState, step.state === 'Current' && styles.currentText]}>{step.state}</Text></View>)}
  </Screen>;
}

const styles = StyleSheet.create({ header: { paddingTop: spacing.md, marginBottom: spacing.lg }, title: { color: colors.ink, fontFamily: fonts.display, fontSize: 34 }, subtitle: { color: colors.muted, fontFamily: fonts.body, fontSize: 15, lineHeight: 21, marginTop: spacing.xs }, search: { minHeight: 50, borderWidth: 1, borderColor: colors.border, borderRadius: 10, flexDirection: 'row', alignItems: 'center', gap: spacing.sm, paddingHorizontal: spacing.md, marginBottom: spacing.md }, input: { flex: 1, color: colors.ink, fontFamily: fonts.body, fontSize: 15 }, filters: { gap: spacing.sm, paddingBottom: spacing.xl }, filter: { minHeight: 40, paddingHorizontal: spacing.md, justifyContent: 'center', borderWidth: 1, borderColor: colors.border, borderRadius: 20 }, filterActive: { backgroundColor: colors.ink, borderColor: colors.ink }, filterText: { color: colors.muted, fontFamily: fonts.body, fontSize: 13, fontWeight: '700' }, filterTextActive: { color: colors.white }, list: { borderTopWidth: 1, borderTopColor: colors.border, marginBottom: spacing.xl }, exerciseRow: { minHeight: 70, borderBottomWidth: 1, borderBottomColor: colors.border, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, exerciseName: { color: colors.ink, fontFamily: fonts.body, fontSize: 16, fontWeight: '700' }, detail: { color: colors.muted, fontFamily: fonts.body, fontSize: 12, marginTop: 4 }, level: { color: colors.muted, fontFamily: fonts.body, fontSize: 12, fontWeight: '700' }, progression: { minHeight: 70, borderTopWidth: 1, borderBottomWidth: 1, borderColor: colors.border, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: spacing.md }, progressionCopy: { flex: 1 }, progressionName: { color: colors.ink, fontFamily: fonts.display, fontSize: 20 }, step: { minHeight: 52, flexDirection: 'row', alignItems: 'center', gap: spacing.sm, borderBottomWidth: 1, borderBottomColor: colors.border }, stepDot: { width: 24, height: 24, borderRadius: 12, borderWidth: 1, borderColor: colors.border, alignItems: 'center', justifyContent: 'center' }, currentDot: { backgroundColor: colors.ink, borderColor: colors.ink }, doneDot: { backgroundColor: colors.success, borderColor: colors.success }, stepIndex: { color: colors.muted, fontFamily: fonts.body, fontSize: 11, fontWeight: '700' }, stepTitle: { flex: 1, color: colors.ink, fontFamily: fonts.body, fontSize: 14 }, stepState: { color: colors.muted, fontFamily: fonts.body, fontSize: 11, fontWeight: '700' }, currentText: { color: colors.ink } });
